Space-Cowboy-2018/AR-Shooter-FrontEnd

- package-lock.json
- store/game.js
- store/index.js
> Game info store #8

- package-lock.json
- screens/ARScene.js
- screens/home.js
> feat(home): socket is now on home and is passed down to children

- screens/ARScene.js
Connects to #10 Closes #10.
crosshair is a tiny cube for now. can change it later.
> Crosshair #10

- screens/ARScene.js
> Update(FE):Changed Crosshair to Sphere

- .babelrc
- .gitignore
- package-lock.json
- package.json
- screens/home.js
Closes #28 connects to #28 
host no longer hard coded.
create a .env file to store host url
SERVER_URL="http://ip_address:3030"
> Secret server #28

- package-lock.json
- screens/ARScene.js
> Feat(FE):Making Lazars

- App.js
- screens/ARScene.js
- screens/AllRooms.js
- screens/GameOver.js
- screens/Home.js
- screens/Rooms.js
- screens/allRooms.js
> fix:(FE):Rename Files

- screens/Rooms.js
> refactor(socket): refactor socket event to be a string constant

- screens/ARScene.js
> Send position interval #47

- screens/ARScene.js
- screens/AllRooms.js
- screens/Home.js
- screens/Rooms.js
> All rooms accept an array of players #62

- screens/ARScene.js
> update(logs): remove console logs

- screens/ARScene.js
> Feat(FE):Add Shootdown-players can only shoot every 500ms

- screens/Lobby.js
> Start game #70

- components/listRooms.js
- screens/AllRooms.js
- screens/Lobby.js
> User can leave room #77

- components/listRooms.js
- screens/AllRooms.js
- screens/Home.js
> Name toast #86

- screens/ARScene.js
- screens/Home.js
Closes #88 
Instead of navigating to the front, a toast shows up.
> feat(toast): toast on disconnect, also name toast is position top

- screens/ARScene.js
> Suppress warnings #95

- screens/Lobby.js
> fix(lobby): swiping back lets you leave room

- screens/ARScene.js
> fix(arScene): turned off update player movement socket on willunmount

- screens/Lobby.js
> fix(handleLeave): removed from willUnmount

- screens/ARScene.js
> Red health bar #100

- screens/ARScene.js
> Crosshair changes on hit

- screens/ARScene.js
- utils/heartPosition.js
> Player position equal heart #125

- screens/ARScene.js
> Add heart to scene #123

- README.md
- screens/ARScene.js
- utils/createLaser.js
- utils/sound.js
> Other players can see shooters lazars #35

- screens/ARScene.js
- utils/heartPosition.js
> Heart listener emitter #124

- screens/ARScene.js
Closes #140 
Please checkout my branch before merging.
> fix(heartHandler): heartHandler now checks to see if this.heart exists
